services:
  # Serviço do banco de dados MySQL
  db:
    image: mysql:8
    container_name: mysql3-db
    restart: always
    environment:
      MYSQL_DATABASE: sisger
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sisger-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

  # Serviço da aplicação Spring Boot - app1
  app1:
    image: lucaseduardo76/sisger-backend:1.0
    container_name: sisger
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sisger?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "80:8080"
    networks:
      - sisger-network


volumes:
  mysql_data:

networks:
  sisger-network:
    driver: bridge
